
X= 'FRONTSP.BO, SEAMECLTD.BO, LTI.BO, GAIL.BO, PERMAGN.BO, PSPPROJECT.BO, CHEMCON.BO, NESTLEIND.BO, BPLPHARMA.BO, SONATSOFTW.BO, AVANTIFEED.BO, SGRL.BO, MARKSANS.BO, POLYCAB.BO, HLEGLAS.BO, NAVINFLUOR.BO, CIGNITITEC.BO, SUYOG.BO, CAMS.BO, SUMICHEM.BO, ICICIGI.BO, RESONANCE.BO, AVANTEL.BO,HINDOILEXP.BO'
Y='MANORG.NS'